@base=http://localhost:8001
//@base=https://secure-api-staging.herokuapp.com
//@base=https://secure-api-prod.herokuapp.com

// Update this with the token that comes back from
// api/auth/register or api/auth/signin
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyLWlkIjoxLCJpYXQiOjE2MDc0Njc0NDEsImV4cCI6MTYwNzQ2ODY0MX0.KCC70w1UVGu67q5UG5cyjaGfgv76dVpm8fwdIWqFd8I

### Hi
GET {{base}}/hi

### Register as a new user
POST {{base}}/api/auth/register
Content-Type: application/json

{
  "email": "fred@acme.com",
  "password": "abc123"
}

### Sign in as existing user
POST {{base}}/api/auth/signin
Content-Type: application/json

{
  "email": "fred@acme.com",
  "password": "abc123"
}

### Sign in (fails)
POST {{base}}/api/auth/signin
Content-Type: application/json

{
  "email": "fred@acme.com",
  "password": "xyz999"
}

### Get own profile
GET {{base}}/api/auth/profile
Authorization: Bearer {{token}}
